version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - "5432:5432"
    networks:
      - mynetwork
networks:
  mynetwork:
